[package]
authors = ["Ben Ruijl <ben@symbolica.io>"]
build = "build.rs"
categories = ["science"]
description = "A blazing fast computer algebra system"
edition = "2024"
keywords = ["algebra", "symbolic", "manipulation", "mathematics", "physics"]
license-file = "License.md"
name = "symbolica"
readme = "Readme.md"
repository = "https://github.com/benruijl/symbolica"
rust-version = "1.85"
version = "0.18.0"

[lib]
crate-type = ["lib"]
name = "symbolica"

[features]
default = ["tracing_max_level_info"]
# if using this, make sure jemalloc is compiled with --disable-initial-exec-tls
# if symbolica is used as a dynamic library (as is the case for the Python API)
faster_alloc = ["tikv-jemallocator"]
# sort functions based on an argument-by-argument comparison
full_fn_cmp = []
mathematica_api = ["wolfram-library-link"]
# create a Python module
python_api = [
    "pyo3/extension-module",
    "numpy",
    "bincode",
    "pyo3-log",
    "tracing/log",
    "pyo3-stub-gen-derive",
]
# export the Python API
python_export = ["pyo3", "numpy", "bincode", "pyo3-stub-gen-derive"]
# generate stubs for Python API
python_stubgen = [
    "python_export",
    "pyo3-stub-gen",
    "symbolica_community/python_stubgen",
]
# build a module that is independent of the specific Python version
python_abi3 = ["pyo3/abi3", "pyo3/abi3-py37"]
tracing_max_level_info = ["tracing/release_max_level_info"]
# import/export objects that do not depend on the state using serde
serde = ["dep:serde", "rug/serde", "symbolica_community/serde"]
# allow importing/exporting of atoms with a state map using bincode
bincode = [
    "dep:bincode",
    "dep:bincode-trait-derive",
    "symbolica_community/bincode",
]
experimental_poly_gcd = []

[dependencies.pyo3]
features = ["abi3", "py-clone", "num-complex"]
optional = true
version = "0.26"

[dependencies]
ahash = "0.8.7"
append-only-vec = "0.1"
bincode = { version = "2.0", optional = true }
brotli = "8.0"
byteorder = "1.5"
bytes = "1.5"
colored = "3.0"
dyn-clone = "1.0"
libloading = "0.8.4"
once_cell = "1.19"
rand = "0.9"
rand_xoshiro = "0.7"
pyo3-stub-gen = { version = "0.14", default-features = false, features = [
    "numpy",
], optional = true }
pyo3-stub-gen-derive = { version = "0.14", optional = true }
rayon = "1.8"
rug = "1.27.0"
numpy = { version = "0.26", optional = true }
self_cell = "1.2.0"
serde = { version = "1.0", features = ["derive"], optional = true }
smallvec = "1.13"
smartstring = "1.0"
tikv-jemallocator = { version = "0.6", optional = true }
tinyjson = "2.5"
tracing = "0.1"
wide = "0.7"
wolfram-library-link = { version = "0.2.9", optional = true }
bincode-trait-derive = { version = "0.1.0", optional = true }
pyo3-log = { version = "0.13", optional = true }
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
symbolica_community = { path = "../symbolica_community" } # TODO: publish
